### ISSUE TITLE
[BUG] App is crashing in the background on notification received event. 

### ISSUE THREAD

**Issue by amandshahu** [Azure/azure-notificationhubs-android#215] opened 2021-08-02 06:45 UTC
**Describe the bug**
NullPointer exception on `onPushNotificationReceived` method of `NotificationListener` interface, due to it app is crashing. this is a background and random crash whenever a notification is received. 

***Exception or Stack Trace***
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.windowsazure.messaging.notificationhubs.NotificationListener.onPushNotificationReceived(android.content.Context, com.google.firebase.messaging.RemoteMessage)' on a null object reference
        at com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver.onMessageReceived(FirebaseReceiver.java:52)
        at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@22.0.0:13)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@22.0.0:8)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@22.0.0:3)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@22.0.0:3)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@22.0.0:1)
        at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.3.0:6)
        at java.lang.Thread.run(Thread.java:764)
```
**To Reproduce**
Unable to understand the reproducing steps, we got to know only through Firebase Crashlytics. 

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
The crashes happening in the background, It should not be crash.

**Screenshots**
![crash](https://user-images.githubusercontent.com/34743123/127815536-0902c01c-73ab-43ad-a8f6-32a348d5dcdd.PNG)

**Setup (please complete the following information):**
 - OS: Any version of Android
 - IDE: Android Studio 4.2.2
 - Version of the Library used: 1.1.6

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by marstr** [comment] 2021-08-16 18:49
Howdy - please review this thread: https://github.com/Azure/azure-notificationhubs-android/issues/191

If you believe it is the same issue:
- This is a big enough "gotcha" that we plan on updating the sample app and documentation to lead people away from this problem.
- We'll close this issue as a duplicate of the old one.

If you believe it is a different issue, please "@" mention me again and I'll take another look!

**Closed** 2021-08-31 07:27 UTC

**Comment by amandshahu** [comment] 2021-08-31 07:29
@marstr Thanks for the update, It is a duplicate issue hence I have closed it.
